spring:
  application:
    name: hevy-companion-api
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATASOURCE_URL}&prepareThreshold=0
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://vgdkmgetpzudngknevhc.supabase.co/auth/v1
  ai:
    google:
      genai:
        api-key: ${AI_API_KEY}
        chat:
          options:
            model: ${AI_MODEL}

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss}){faint} %clr(%5p) %clr(->){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
