spring.application.name=hevy-companion-api
spring.config.import=optional:file:${HEVY_SECRETS_PATH}

spring.ai.google.genai.api-key=${AI_API_KEY}
spring.ai.google.genai.chat.options.model=${AI_MODEL}

spring.datasource.url= ${DATASOURCE_URL}&prepareThreshold=0
spring.jpa.hibernate.ddl-auto=update

# Simplified, colorful output that fits on one line
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%5p) %clr(->){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n

# Supabase JWT Issuer (Used by Spring Security OAuth2 Resource Server to fetch ES256 public keys)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://vgdkmgetpzudngknevhc.supabase.co/auth/v1